theme: jekyll-theme-minimal
title: 💻💭

github_username:  skirt-owner
avatar: https://www.britannica.com/animal/animal
aboutme: Hi, this is Lijia Yu. I made the Freshman21 theme. Please enjoy it. # these are shown on aboutme-box(sidebar).
aboutme_photo: https://www.britannica.com/animal/animal
